version: "3"

services:
  postgis:
    container_name: 'postgis'
    image: 'kartoza/postgis:9.6-2.4'
    env_file:
      - env.cfg
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    container_name: 'redis'
    image: 'redis'
    expose:
      - "6379"

  web:
    container_name: 'web'
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - env.cfg
    depends_on:
      - postgis
      - redis
    links:
      - "postgis"
      - "redis"

volumes:
  pgdata:
