version: "3"

services:
  postgis:
    container_name: 'postgis'
    image: 'kartoza/postgis:9.6-2.4'
    env_file:
      - env.cfg
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  redis:
    container_name: 'redis'
    image: 'redis'
    expose:
      - "6379"

  nginx:
    container_name: 'nginx'
    build: ./docker/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - web_data:/dengue-backend
      - nginx_log:/var/log/nginx
    depends_on:
      - web

  web:
    container_name: 'web'
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - env.cfg
    depends_on:
      - postgis
      - redis
    volumes:
      - web_data:/dengue-backend
    links:
      - "postgis"
      - "redis"

volumes:
  pg_data:
  nginx_log:
  web_data:
